export const leaderBoard = [
  {
    id: 1,
    initials: 'AA',
    name: 'Ashiqul Amin',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 34,
  },
  {
    id: 2,
    initials: 'HM',
    name: 'Hussain Al Muhee',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 31,
  },
  {
    id: 3,
    initials: 'BS',
    name: 'Biplab Chandra Sarker',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 35,
  },
  {
    id: 4,
    initials: 'AT',
    name: 'Ahnaf Tahmid',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 30,
  },
  {
    id: 5,
    initials: 'HN',
    name: 'Humaira Nomrota',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 36,
  },
  {
    id: 6,
    initials: 'MH',
    name: 'Mashiur Ahmed Hridoy',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 40,
  },
  {
    id: 7,
    initials: 'NN',
    name: 'Neyem Nawaf',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 40,
  },
  {
    id: 8,
    initials: 'AT',
    name: 'Ahnaf Tahmid',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 30,
  },
  {
    id: 9,
    initials: 'BS',
    name: 'Biplab Chandra Sarker',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 35,
  },
  {
    id: 10,
    initials: 'AA',
    name: 'Ashiqul Amin',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 34,
  },
  {
    id: 11,
    initials: 'NN',
    name: 'Neyem Nawaf',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 40,
  },
  {
    id: 12,
    initials: 'HM',
    name: 'Hussain Al Muhee',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 31,
  },
  {
    id: 13,
    initials: 'NN',
    name: 'Neyem Nawaf',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 40,
  },
  {
    id: 14,
    initials: 'NN',
    name: 'Neyem Nawaf',
    role: 'of leads',
    username: 'ashiqulamin',
    totalLeads: 40,
  },
];
